In [4]:
format compact

# Programmeringsintroduktion

### i MATLAB

Matematikprogrammet, Örebro Universitet (2021)

Hugo U.R. Strand

Kurshemsida: https://git.oru.se/hosd/matlab-intro-ht21/

# Föreläsningar

- F1 Programmeringskoncept
  - variabler, operatorer, och flödeskontroll
- F2 Procedurell programmering
  - funktioner, rekursion, och algoritmer
- F3 Visualisering
- F4 Multi-dimensionella arrayer

# Datorövningar

- Ö1 Matlab On Ramp
- Ö2 Sorteringsalgoritmer
- Ö3 Rot-lösar-algoritmer
- Ö4 Fraktaler

# Föreläsningar i Jupyter

För att interaktivt köra Matlab

In [26]:
% Detta är en kod-kommentar i Matlab

% anropa Matlab funktionen "disp"

disp('Hello Matlab World!') 

Hello Matlab World!


# Tillgång till MATLAB

- Datorsalarna
- På webben (registrera på MathWorks hemsida med @oru.se email-adress)
- Ladda hem genom universitetet

[MATLAB för studenter vid ORU](https://www.oru.se/english/study/student-services/it-and-printing/it/software/matlab/)


# Föreläsning 1

- Variabler och tilldelning
- Aritmetiska operationer
- Flödeskontroll
- Container-datatyper 

# Variabler och tilldelning

- Heltal, flyttal, boolska variabler
- Text strängar

In [27]:
% Tilldela variabeln "a", heltalsvärdet 10

a = 10

a =
    10


In [28]:
% Tilldela varaiabeln "b", flyttalsvärdet 3.1415

b = 3.1415

b =
    3.1415


In [29]:
% Aritmetiska operationer

c = a / b

d = c + 1.5 - b

e = a^2

c =
    3.1832
d =
    1.5417
e =
   100


In [30]:
% Logiska uttryck / tester

f = a > 1
h = a == b

f =
  logical
   1
h =
  logical
   0


In [31]:
% Variabel på båda sidorna likhetstecknet i en tilldelning

num = 1
num = num + 1
num = num + 1

num =
     1
num =
     2
num =
     3


In [36]:
% Text, "strängar" av bokstäver

t = "Hello Matlab!"

msg = "The value of a is " + num2str(a) + "."

t = 
    "Hello Matlab!"
msg = 
    "The value of a is 10."


# Arrayer

Syntax: `x = [a, b, c, ...]`

Indexering: `x(i)`

`end` är sista elementet & `x(end+1) = a` lägger till `a` sist i listan

In [37]:
x = [2, 4, 8, 16]

x =
     2     4     8    16


In [38]:
a = x(2)
b = x(end)

a =
     4
b =
    16


In [39]:
x(end+1) = 1337

x =
           2           4           8          16        1337


# "Range": serier av tal

Syntax: 
```
x = start:end
x = start:step:end
```

In [40]:
y = 1:10
z = 1:2:11
q = 0:0.2:1

y =
     1     2     3     4     5     6     7     8     9    10
z =
     1     3     5     7     9    11
q =
         0    0.2000    0.4000    0.6000    0.8000    1.0000


# Flödeskontroll

Reserverade nyckelord (i Matlab:s programmeringsspråk)

- `for`, `end`
- `if`, `elseif`, `else`, `end`
- `break`, `continue`

- `while`, `end`
- `switch`, `case`, `otherwise`, `end`

# Repetition med `for`-loop

Exekvera samma kod upprepade gånger

In [42]:
for x = 1:10
    disp(x)
end

     1
     2
     3
     4
     5
     6
     7
     8
     9
    10


In [43]:
% Ex: Summera alla tal från 1 till och med 10

n = 0;
for x = 1:10
    n = n + x;
end
disp("n = " + num2str(n))

n = 55


In [44]:
% Snabb version mha funktionen "sum"

n = sum(1:10)

n =
    55


# Flödeskontroll med `if`-`elseif`-`else`

Kontrollera vilken kod som exekveras baserat på logiska uttryck

In [47]:
for x = 0:9
    if x == 0
        disp(num2str(x) + " is special")
    elseif rem(x, 2) == 0
        disp(num2str(x) + " is even")
    else
        disp(num2str(x) + " is odd")
    end
end

0 is special
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


# Flödeskontroll med `break`-`continue`

- `break` : avbryter en `for` eller `while` loop
- `continue` : hoppa direkt till nästa steg i en `for`/`while` loop

In [48]:
for x = 1:10
    if x < 5
        continue
    end
    if x == 8
        break
    end
    disp(x)
end

     5
     6
     7


# Repetition med `while`-loop

Loop konstruktion med logist test för att fortsätta loopandet.

In [49]:
x = 1;
while x < 100
    x = x + 1;
end
x

x =
   100


In [50]:
% Evighets "while"-loop med "break" avslut

y = 1;
while true
    y = y * 2;
    if y > 10e5
        break
    end
end
y

y =
     1048576


# Flödeskontroll med  `switch`-`case`-`otherwise`

- Liknande funktionalitet som `if`-`elseif` satser

- Lämpligt vid val mellan många möjliga fall med enkel matchning

In [ ]:
method = 'bubble sort';

switch(method)
    case 'shell sort'
        disp('Anropa shell sort')
    case 'bubble sort'
        disp('Anropa bubble sort')
    case 'quick sort'
        disp('Anropa quick sort')
    otherwise
        disp('Okänd metod!')
end

# Container datatyper

- Arrayer (multi dimensionella arrayer med element av samma typ)
- Strukturer (flera delobjekt av olika typ)
- Table & CellArray

## Multi-dimensionella arrayer

In [51]:
% Endimensionell array

x = [1, 8, 4]

size(x)

x =
     1     8     4
ans =
     1     3


In [52]:
% Två-dimensionell array (matris)

y = [10, 3; 4, 9]

size(y)

y =
    10     3
     4     9
ans =
     2     2


In [53]:
% Array skapande: ones, zeros, rand

x = ones([3, 6])
y = zeros([3, 4])
z = rand([3, 2])

x =
     1     1     1     1     1     1
     1     1     1     1     1     1
     1     1     1     1     1     1
y =
     0     0     0     0
     0     0     0     0
     0     0     0     0
z =
    0.8147    0.9134
    0.9058    0.6324
    0.1270    0.0975


In [54]:
% Sammansättning: cat

h = cat(2, x, y)

h =
     1     1     1     1     1     1     0     0     0     0
     1     1     1     1     1     1     0     0     0     0
     1     1     1     1     1     1     0     0     0     0


# Container typer `struct`, `CellArray`, `table`

- `struct` : namngivna medlemsvariabler
- `cellarray` : array med element av olika typ
- `table` : tabell container

In [55]:
s = struct('weight', 10., 'height', 123.)

s.weight

s = 
  struct with fields:

    weight: 10
    height: 123
ans =
    10


In [56]:
% CellArray

ca = {10.12, 100, 'Hej!'}

ca =
  1x3 cell array
    {[10.1200]}    {[100]}    {'Hej!'}


In [57]:
% table

weight = [0.1, 3.]';
height = [10., 2.]';
t = table(weight, height)

t.height

t =
  2x2 table
    weight    height
    ______    ______
     0.1        10  
       3         2  
ans =
    10
     2


In [58]:
% struct array från tabell
s = table2struct(t)

s.weight

s = 
  2x1 struct array with fields:
    weight
    height
ans =
    0.1000
ans =
     3


# Övning 1

- Summera alla tal från 1 till 10000 och skriv ut resultatet
  - använd en `for` loop
  - Svar: 50005000

In [ ]:
n = 0;
for x = 1:10000
    n = n + x;
end
n

# Övning 2

- Summera alla udda tal från 1 till 10000 och skriv ut resultatet
  - använd en `while` loop
  - Svar: 25000000

In [ ]:
n = 0;
x = 1;
while x <= 10000
    n = n + x;
    x = x + 2;
end
n

# Övning 3

- Summera alla tal som är jämnt delbara med 3 mellan 1 och 10000 och skriv ut resultatet
  - Svar: 16668333

In [ ]:
n = 0;
for x = 1:10000
    if rem(x, 3) == 0
        n = n + x;
    end
end
n

# Slut på Föreläsning 1

## Övning 1 - Matlab On Ramp

<https://git.oru.se/hosd/matlab-intro-ht21/>