In [1]:
format compact

# Programmeringsintroduktion

### i MATLAB

Matematikerprogrammet, Örebro Universitet

Hugo U.R. Strand

Kurshemsida: https://git.oru.se/hosd/matlab-intro/

# Föreläsningar

- F1 Programmeringskoncept
  - variabler, operatorer, och flödeskontroll
- F2 Procedurell programmering
  - funktioner, rekursion, och algoritmer
- F3 Visualisering
- F4 Multi-dimensionella arrayer

# Datorövningar

- Ö1 Matlab On Ramp
- Ö2 Sorteringsalgoritmer
- Ö3 Rot-lösar-algoritmer
- Ö4 Fraktaler

# Ett första exempel

Vi kommer att köra Matlab interaktivt på föreläsningarna

In [2]:
% Detta är en kod-kommentar i Matlab

% anropa Matlab funktionen "disp"

disp('Hello Matlab World!') 

Hello Matlab World!


# Tillgång till MATLAB

- Datorsalarna
- På webben (registrera på MathWorks hemsida)
- Ladda hem genom universitetet

[MATLAB för studenter vid ORU](https://www.oru.se/english/study/student-services/it-and-printing/it/software/matlab/)


# Föreläsning 1

- Variabler och tilldelning
- Aritmetiska operationer
- Flödeskontroll
- Arrayer

# Variabler och tilldelning

- Heltal, flyttal, boolska variabler
- Text-strängar

In [3]:
% Tilldela variabeln "a", heltalsvärdet 10

a = 10

a =
    10


In [4]:
% Tilldela varaiabeln "b", flyttalsvärdet 3.1415

b = 3.1415

b =
    3.1415


In [5]:
% Aritmetiska operationer

c = a / b

d = c + 1.5 - b

e = a^2

c =
    3.1832
d =
    1.5417
e =
   100


In [6]:
% Logiska uttryck / tester

f = a > 1
h = a == b

f =
  logical
   1
h =
  logical
   0


In [7]:
% Variabel på båda sidorna likhetstecknet i en tilldelning

num = 1
num = num + 1
num = num + 1

num =
     1
num =
     2
num =
     3


In [8]:
% Text, "strängar" av bokstäver

t = "Hello Matlab!"

msg = "The value of a is " + num2str(a) + "."

t = 
    "Hello Matlab!"
msg = 
    "The value of a is 10."


# Arrayer

Syntax: `x = [a, b, c, ...]`

Indexering: `x(i)`

`end` är sista elementet & `x(end+1) = a` lägger till `a` sist i listan

In [9]:
x = [2, 4, 8, 16]

x =
     2     4     8    16


In [10]:
a = x(2)
b = x(end)

a =
     4
b =
    16


In [11]:
x(end+1) = 1337

x =
           2           4           8          16        1337


# "Range": serier av tal

Syntax: 
```
x = start:end
x = start:step:end
```

In [12]:
y = 1:10
z = 1:2:11
q = 0:0.2:1

y =
     1     2     3     4     5     6     7     8     9    10
z =
     1     3     5     7     9    11
q =
         0    0.2000    0.4000    0.6000    0.8000    1.0000


# Multi-dimensionella arrayer


In [13]:
% En-dimensionell array

x = [1, 8, 4]

size(x)

x =
     1     8     4
ans =
     1     3


In [14]:
% Två-dimensionell array (matris)

y = [10, 3; 4, 9]

size(y)

y =
    10     3
     4     9
ans =
     2     2


In [15]:
% Array-skapande: ones, zeros, rand

x = ones([3, 6])
y = zeros([3, 4])
z = rand([3, 2])

x =
     1     1     1     1     1     1
     1     1     1     1     1     1
     1     1     1     1     1     1
y =
     0     0     0     0
     0     0     0     0
     0     0     0     0
z =
    0.8147    0.9134
    0.9058    0.6324
    0.1270    0.0975


In [16]:
% Sammansättning: cat

h = cat(2, x, y)

h =
     1     1     1     1     1     1     0     0     0     0
     1     1     1     1     1     1     0     0     0     0
     1     1     1     1     1     1     0     0     0     0


# Flödeskontroll

Reserverade nyckelord (i Matlab:s programmeringsspråk)

- `for`, `end`
- `if`, `elseif`, `else`, `end`
- `break`, `continue`

- `while`, `end`
- `switch`, `case`, `otherwise`, `end`

# Repetition med `for`-loop

Exekvera samma kod upprepade gånger

In [17]:
for x = 1:10
    disp(x)
end

     1
     2
     3
     4
     5
     6
     7
     8
     9
    10


In [18]:
% Ex: Summera alla tal från 1 till och med 10

n = 0;
for x = 1:10
    n = n + x;
end
disp("n = " + num2str(n))

n = 55


In [19]:
% Snabb version mha funktionen "sum"

n = sum(1:10)

n =
    55


# Flödeskontroll med `if`-`elseif`-`else`

Kontrollera vilken kod som exekveras baserat på logiska uttryck

In [20]:
for x = 0:9
    if x == 0
        disp(num2str(x) + " is special")
    elseif rem(x, 2) == 0
        disp(num2str(x) + " is even")
    else
        disp(num2str(x) + " is odd")
    end
end

0 is special
1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


# Flödeskontroll med `break`-`continue`

- `break` : avbryter en `for` eller `while` loop
- `continue` : hoppa direkt till nästa steg i en `for`/`while` loop

In [21]:
for x = 1:10
    if x < 5
        continue
    end
    if x == 8
        break
    end
    disp(x)
end

     5
     6
     7


# Repetition med `while`-loop

Loop konstruktion med logist test för att fortsätta loopandet.

In [22]:
x = 1;
while x < 100
    x = x + 1;
end
x

x =
   100


In [23]:
% Evighets "while"-loop med "break" avslut

y = 1;
while true
    y = y * 2;
    if y > 10e5
        break
    end
end
y

y =
     1048576


# Övningsexempel

## Övning 1

- Summera alla tal från 1 till 10000 och skriv ut resultatet
  - använd en `for` loop
  - Svar: 50005000

In [24]:
n = 0;
for x = 1:10000
    n = n + x;
end
n

n =
    50005000


## Övning 2

- Summera alla udda tal från 1 till 10000 och skriv ut resultatet
  - använd en `while` loop
  - Svar: 25000000

In [25]:
n = 0;
x = 1;
while x <= 10000
    n = n + x;
    x = x + 2;
end
n

n =
    25000000


## Övning 3

- Summera alla tal som är jämnt delbara med 3 mellan 1 och 10000 och skriv ut resultatet
  - Funktionen `rem(a,b)` ger resten vid heltalsdivision `a/b`
  - Svar: 16668333

In [26]:
n = 0;
for x = 1:10000
    if rem(x, 3) == 0
        n = n + x;
    end
end
n

n =
    16668333


# Slut på Föreläsning 1

## Övning 1 - Matlab On Ramp

<https://git.oru.se/hosd/matlab-intro/>