In [1]:
format compact

# Övning 2: Sorterings algoritmer

<https://en.wikipedia.org/wiki/Sorting_algorithm>

### Uppgift 1

In [2]:
%%file bubble_sort.m

function s = bubble_sort(l)
    s = zeros(size(l));
    s(:) = l;
    for i = 1:length(l)-1
        for j = 1:length(l)-1
           if s(j) > s(j+1)
               % Exchange positions of the two numbers
               tmp = s(j);
               s(j) = s(j + 1);
               s(j + 1) = tmp;
           end
        end
    end
end

Created file '/Users/hugstr/dev/matlab-intro/Övningar/lösningsförslag/bubble_sort.m'.


In [3]:
l = [8, 4, 6, 1]
s = bubble_sort(l)

l =
     8     4     6     1
s =
     1     4     6     8


In [4]:
% Testa bubble_sort med sort funktionen
l = randn(1, 100);
assert(all(sort(l) == bubble_sort(l)))

### Extra-uppgift 1

In [5]:
%%file quick_sort.m

function s = quick_sort(l)
    s = quick_sort_recursion(l, 1, length(l));
end

function s = quick_sort_recursion(l, lo, hi)
    if lo >= 1 && hi >= 1 && lo < hi
        [p, l] = partition(l, lo, hi);
        l = quick_sort_recursion(l, lo, p - 1);
        l = quick_sort_recursion(l, p + 1, hi);
    end
    s = l;
end

function [p, s] = partition(l, lo, hi)
    pivot = l(hi);
    i = lo - 1;
    for j = lo:hi
        if l(j) <= pivot
            i = i + 1;
            tmp = l(i);
            l(i) = l(j);
            l(j) = tmp;
        end
    end
    p = i;
    s = l;
end

Created file '/Users/hugstr/dev/matlab-intro/Övningar/lösningsförslag/quick_sort.m'.


In [6]:
l = [8, 4, 6, 1, 3, 8, 4]
s = quick_sort(l)

l =
     8     4     6     1     3     8     4
s =
     1     3     4     4     6     8     8


In [7]:
% Testa quick_sort med sort funktionen
l = randn(1, 100);
assert(all(sort(l) == quick_sort(l)))